serviceAccount:
  create: false
  name: "${existingServiceAccount}"

# https://thanos.io/tip/thanos/storage.md/#s3
objstoreConfig: |-
  type: S3
  config:
    bucket: "${s3Bucket}"
    endpoint: s3.us-west-2.amazonaws.com

image:
  registry: docker.io
  repository: bitnami/thanos
  tag: 0.32.2-debian-11-r2

query:
  enabled: true
  replicaCount: 1
  stores:
    - thanos-storegateway.observability.svc.cluster.local:10901
    - prometheus-kube-prometheus-thanos-discovery.observability.svc.cluster.local:10901

queryFrontend:
  enabled: true

compactor:
  enabled: true
  serviceAccount:
    create: false
    existingServiceAccount: "${existingServiceAccount}"
  retentionResolutionRaw: 30d
  retentionResolution5m: 30d
  retentionResolution1h: 45d

storegateway:
  enabled: true
  serviceAccount:
    create: false
    existingServiceAccount: "${existingServiceAccount}"

receive:
  enabled: false

metrics:
  enabled: false

bucketweb:
  enabled: false

ruler:
  enabled: false