{
 "title": "Cilium Policy Verdicts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "query_result(label_replace(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\"}, \"workload\", \"$1\", \"destination\", \"(.+)\") OR label_replace(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\"}, \"workload\", \"$1\", \"source\", \"(.+)\"))"
    }
   },
   {
    "name": "other_namespace",
    "label": "other namespace",
    "query": {
     "query": "query_result(label_replace(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\", destination=~\"$workload\"}, \"other_namespace\", \"$1\", \"source_namespace\", \"(.+)\") OR label_replace(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\", source=~\"$workload\"}, \"other_namespace\", \"$1\", \"destination_namespace\", \"(.+)\"))"
    }
   },
   {
    "name": "other_workload",
    "label": "other workload",
    "query": {
     "query": "query_result(label_replace(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\",  destination=~\"$workload\", source_namespace=~\"$other_namespace|\"}, \"workload\", \"$1\", \"source\", \"(.+)\") OR label_replace(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\",  source=~\"$workload\", destination_namespace=~\"$other_namespace|\"}, \"workload\", \"$1\", \"destination\", \"(.+)\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress Policy Verdict Rate per Minute by Match Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (match) (rate(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\", destination=~\"$workload\", source_namespace=~\"$other_namespace|\", source=~\"$other_workload\"}[$__rate_interval])) * 60",
     "legendFormat": "{{match}}"
    }
   ]
  },
  {
   "title": "Egress Policy Verdict Rate per Minute by Match Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (match) (rate(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\", source=~\"$workload\", destination_namespace=~\"$other_namespace|\", destination=~\"$other_workload\"}[$__rate_interval])) * 60",
     "legendFormat": "{{match}}"
    }
   ]
  },
  {
   "title": "Ingress Policy Verdict Rate per Minute by Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (action) (rate(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\", destination=~\"$workload\", source_namespace=~\"$other_namespace|\", source=~\"$other_workload\"}[$__rate_interval])) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Egress Policy Verdict Rate per Minute by Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\", source=~\"$workload\", destination_namespace=~\"$other_namespace|\", destination=~\"$other_workload\"}[$__rate_interval])) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Current Ingress Policy Verdict Rate Per Minute",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (source_namespace, source, destination_namespace, destination, match, action) (rate(hubble_policy_verdicts_total{direction=\"ingress\", destination_namespace=~\"$namespace\", destination=~\"$workload\", source_namespace=~\"$other_namespace|\", source=~\"$other_workload\"}[$__rate_interval])) * 60",
     "legendFormat": "source: {{source_namespace}}/{{source}} destination: {{destination_namespace}}/{{destination}} match: {{match}} action: {{action}}"
    }
   ]
  },
  {
   "title": "Current Egress Policy Verdict Rate Per Minute",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (destination_namespace, destination, source_namespace, source, match, action) (rate(hubble_policy_verdicts_total{direction=\"egress\", source_namespace=~\"$namespace\", source=~\"$workload\", destination_namespace=~\"$other_namespace|\", destination=~\"$other_workload\"}[$__rate_interval])) * 60",
     "legendFormat": "destination: {{destination_namespace}}/{{destination}} source:  {{source_namespace}}/{{source}} match: {{match}} action: {{action}}"
    }
   ]
  }
 ]
}